print("Day Converter Program")
Day=int(input("Input number of days-->"))
print(Day,"Days--> Hour",24*Day, "Hour")
print(Day,"Days--> Mintes",60*24*Day, "Minutes")
print(Day,"Days--> Seconds",60*60*24*Day, "Seconds")