num1=input("Input your First Number:\n")
num2=input("Input your Second Number:\n")
num3=input("Input your Third Number:\n")
num4=input("Input your Fourth Number:\n")
num5=input("Input your Fifth Number:\n")
a= float(num1)
a1= complex(num1)
print("float of",num1,"Equal",a)
print("complex of",num1,"Equal",a1)
b= float(num2)
b2= complex(num2)
print("float of",num2,"Equal",b)
print("complex of",num2,"Equal",b2)
c= float(num3)
c3= complex(num3)
print("float of",num3,"Equal",c)
print("complex of",num3,"Equal",c3)
d= float(num4)
d4= complex(num4)
print("float of",num4,"Equal",d)
print("complex of",num4,"Equal",d4)
e= float(num5)
e5= complex(num5)
print("float of",num5,"Equal",e)
print("complex of",num5,"Equal",e5)
